spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pokemon-route
          uri: lb://poke
          predicates:
            - Path=/api/pokemon/{name}
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
